name: Test, Build, Push
on:
  push:
    paths-ignore:
      - ".editorconfig"
      - "LICENSE"
      - "README.md"

jobs:
  test-build-push:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: ghcr.io/figwasp/figwasp
      SEMVER_MAJOR: "2"
      SEMVER_MINOR: "2.0"
      SEMVER_PATCH: "2.0.0"

    steps:
      - name: Docker Login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.17"

      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache Go Modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Go Test
        run: CGO_ENABLED=0 go test -v ./test

      - name: Go Build
        run: CGO_ENABLED=0 GOOS=linux go build ./cmd/figwasp

      - name: Docker Build
        run: |
          docker build \
            -t $IMAGE_NAME:latest \
            -t $IMAGE_NAME:$SEMVER_MAJOR \
            -t $IMAGE_NAME:$SEMVER_MINOR \
            -t $IMAGE_NAME:$SEMVER_PATCH \
            .

      - name: Docker Push
        run: docker push --all-tags $IMAGE_NAME
